spring:
  datasource:
    url: jdbc:sqlite:D:/sqlite/test.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.wang.luck.draw.entity #实体扫描，多个package用逗号或者分号分隔